// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tegpyalokurixuvgeuks.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRlZ3B5YWxva3VyaXh1dmdldWtzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA1MTQ4NzEsImV4cCI6MjA3NjA5MDg3MX0.OKeYoutBY8UM3h8sLqSyOKm5m1kamTAY_fq0qlViPME";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});